name: ServerSleep
version: '${version}'
main: com.loyal0713.serversleep.ServerSleep
authors: [Loyal0713]
api-version: '1.13'
description: Allows configuring the percentage of players needed to sleep to skip the night
commands:
  serversleep:
    description: View or configure the sleep percentage
    usage: /serversleep [percent <0-100>] [reload]
    permission: serversleep.command
    permission-message: You do not have permission to use this command!
permissions:
  serversleep.command:
    description: Allows use of the /serversleep command
    default: op
